# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "mshaikhgd/fastly-poc"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "goodrx"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    registry: goodrx
    image_name: "mshaikhgd/fastly-poc"
    disable_push: true
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "ls"
    stage: "test"
    
  deploy-dev:
    title: "Deploying to dev"
    image: hashicorp/terraform:light
    stage: "deploy"
    type: freestyle
    working_directory: '${{CLONE_STEP_NAME}}'
    arguments:
      image: 'mshaikhgd/fastly-poc'
      commands:
        - mustache www-staging.goodrx.com/mustache.json main.tf.mustache main.tf
        - cat main.tf
        - terraform www-staging.goodrx.com apply
          -auto-approve
          -var fastly_api_key=${FASTLY_API_KEY}

    
  deploy-prod:
    title: "Deploying to Prod"
    image: hashicorp/terraform:light
    stage : "deploy"
    when:
      branch:
        only:
          - master
          - develop
  

